In [1]:
#how to create a series from a list, numpy array and dict?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int32


In [2]:
# how to convert the index of a series into a columns of a dataframes?
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

In [3]:
# how to combine many series to from a dataframe? 
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
# Solution 1
df = pd.concat([ser1, ser2], axis=1)
df.head()
# Solution 2 
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
df.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [4]:
# How to assign name to the series index?
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [5]:
# How to get items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [6]:
 # How to get the items not common to both series A and series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser_u = pd.Series(np.union1d(ser1, ser2)) #union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) #intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [7]:
# How to get the minimum, 25th percentile, median, 75th, and max of numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [8]:
# How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size = 30)))
ser.value_counts()

b    8
c    7
g    5
h    5
d    2
e    2
a    1
dtype: int64

In [9]:
# How to keep only top 2 most frequent values as it is and replace everything else as 'Other'?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print('Top 2 Freq:', ser.value_counts())
ser[~ser.isin(ser.value_counts().index[0:2])] = 'Other'
ser

Top 2 Freq: 3    7
2    2
4    2
1    1
dtype: int64


0         2
1         3
2         3
3         3
4         3
5     Other
6     Other
7         3
8         3
9         2
10        3
11    Other
dtype: object

In [10]:
# How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(20))
print(ser.head())
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1],
        labels = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th','9th', '10th']).head()

0    0.792632
1    0.970528
2    0.831602
3    0.049370
4    0.209661
dtype: float64


0     8th
1    10th
2    10th
3     2nd
4     3rd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [11]:
# How to convert a numpy array to a dataframe of given shape
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7,5))
df

0  1  2  3  4
0  1  6  1  3  8
1  8  5  4  1  3
2  7  9  5  2  5
3  9  7  2  3  1
4  2  7  2  9  6
5  4  5  3  4  1
6  3  7  3  9  2

In [12]:
# How to find the positions of numbers that are multiples of 3 from a series?
ser = pd.Series(np.random.randint(1, 10, 7))
ser
#np.argwhere(ser % 3 == 0)
# i can't solve the problem, i will look again later.



0    5
1    7
2    6
3    9
4    7
5    6
6    1
dtype: int32

In [13]:
# How to extract items at given position from a series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [14]:
# How to stack two series vertically and horizontally?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
# Vertical
ser1.append(ser2)
# Horizontal
df = pd.concat([ser1, ser2], axis=1)
df

C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\1222463864.py:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser1.append(ser2)


0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [15]:
# How to get positions of items of series A in another series B?
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]
# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [16]:
# How to compute the mean squared error on an truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
np.mean((truth-pred)**2)

0.3302642479491031

In [17]:
# How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))


0    3
1    2
2    4
3    4
dtype: int64

In [18]:
# How to compute difference of differences between consequtive numbers of a series?
ser = pd.Series([1, 3 , 6, 9, 15, 21, 27, 35])
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 3.0, 6.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 0.0, 3.0, 0.0, 0.0, 2.0]


In [19]:
# How to convert a series of date-string to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))
# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [20]:
# How to get the day of month, week number, day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
# day of month
print('Date: ', ser_ts.dt.day.tolist())
# week number
print('Week number: ', ser_ts.dt.weekofyear.tolist())
# day of year
print('Day number of year: ', ser_ts.dt.dayofyear.tolist())
# day of week
print('Day of week: ', ser_ts.dt.day_of_week.tolist())
# i can't solve 'day of week', i will look again later.



Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  [4, 2, 5, 3, 0, 5]


C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\1222662970.py:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print('Week number: ', ser_ts.dt.weekofyear.tolist())


In [21]:
# How to convert year-month string to dates corresponding to the 4th day of the month?
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))
# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str')+ '-' + '04'
# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]
# Solution 2
ser.map(lambda x: parse('04' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [22]:
# How to filter words that contaion atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0)for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [23]:
# How to filter valid emails from a series ?
emails = pd.Series(['buying book at amozom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
#pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
# Solution 1
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]
# Solution 2
emails.str.findall(pattern, flags=re.IGNORECASE)
# Solution 3
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [24]:
# How to get the mena of a series grouped by another series?
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
weight.groupby(fruit).mean()


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'banana', 'apple', 'carrot', 'banana', 'apple', 'carrot', 'apple', 'carrot', 'apple']


apple     6.75
banana    3.50
carrot    5.25
dtype: float64

In [25]:
# How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
# Solution
sum((p - q)**2)**.5
# Solution(using func)
np.linalg.norm(p-q)

18.16590212458495

In [26]:
# How to find all the local maxina(or peaks) in a numeric series?
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

In [27]:
# How to replace missing spaces in a string with the least frequent character?
my_str = 'dbc deb abed gade'
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
b    3
     3
e    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

In [28]:
# How to create a TimeSeris starting '2000-01-01' and 10 weekends(saturdays) after that having random numbers as values?
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq = 'W-SAT'))
ser

2000-01-01    1
2000-01-08    3
2000-01-15    5
2000-01-22    1
2000-01-29    6
2000-02-05    8
2000-02-12    2
2000-02-19    3
2000-02-26    1
2000-03-04    9
Freq: W-SAT, dtype: int32

In [29]:
# How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [30]:
# How to compute the autocorrelations of a numeric series?
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.21, 0.34, 0.05, 0.54, 0.59, 0.24, 0.25, -0.2, 0.35, 0.01]
Lag having highest correlation:  5


In [31]:
#How to import only every nth row from a csv file to create a dataframe?
# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
print(df2.head())


# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
print(df2.head())
# Solution 3: Use csv reader
#import csv          
#with open('BostonHousing.csv', 'r') as f:
#    reader = csv.reader(f)
#   out = []
#    for i, row in enumerate(reader):
#        if i%50 == 0:
#            out.append(row)

#df2 = pd.DataFrame(out[1:], columns=out[0])
#print(df2.head())
# i can't solve the problem, i will look again later

C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\846289175.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\846289175.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\846289175.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\846289175.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
C:\Users\fatih\AppData\Local\Temp\ipykernel_7872\846289175.py:6:

        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  

In [32]:
# How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

In [33]:
# How to import only specified columns from a csv file?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [34]:
# How to get the nrows, ncolumns, datatype, summary stats of each columns of a dataframe?
# Also get the array and list equivalent.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# number of rows and columns
print(df.shape)
# datatypes
print(df.dtypes)
# how many columns under each dtype
print(df.dtypes.value_counts())
# summary statisctics
df_stats = df.describe()
# numpy array
df_arr = df.values
# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


In [35]:
# How to extract the row and column number of a particular cell with given criterion?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]
# Get Row and Columns number
row, col = np.where(df.values == np.max(df.Price))
# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]
# Alternates
df.at[row[0], 'Price']
#df.get_value(row[0], 'Price')
# The difference between `iat` - `iloc` vs `at` - `loc` is:
# `iat` snd `iloc` accepts row and column numbers. 
# Whereas `at` and `loc` accepts index and column names.

61.9

In [36]:
# How to rename a specific columns in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
# Solution
# Step1
df = df.rename(columns = {'Type': 'CarType'})
# or 
df.columns.values[2] = 'CarType'
# Step2
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [37]:
# How to check if a dataframe has any missing values?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.isnull().values.any())


True


In [38]:
# How to count the number of missing values in each column?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
n_missing_each_col = df.apply(lambda x: x.isnull().sum())
n_missing_each_col.argmax()



23

In [39]:
# How to replace missing values of multiple numeric columns with the mean?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [40]:
# How to use apply function on existing columns with global variables as additional arguments?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))


In [41]:
# How to select a specific columns from a dataframe as a dataframe instead of a series?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

In [42]:
# How to change the order of columns of a dataframe?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
# Solution Q1
df[list['cbade']]
#Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]
df1 = switch_columns(df, 'a', 'c')
# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)
   


In [43]:
# How to set the number of rows and columns displayed in the output?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df
# Show all available options
#pd.describe_option()

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [44]:
# How to format or suppress scientific notations in a pandas dataframe?
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
#df
# Solution 1: Rounding
#df.round(4)
# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
#or
df.applymap(lambda x: '%.4f' % x)
# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)
# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)
# Reset/undo float formatting
pd.options.display.float_format = None


   random
0  0.0002
1  0.0000
2  0.0000
3  0.0537


In [45]:
# How to format all the values in a dataframe as percentages?
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

In [46]:
# How to filter every nth row in a dataframe ?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [47]:
# How create a primary key index by combining relevant columns?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [48]:
# How to get the row number of the nth largest value in a column?
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
n = 5
df['a'].argsort()[::-1][n]

8

In [49]:
# How to find the position of the nth largest value greater than a given value?
from pandas import array


ser = pd.Series(np.random.randint(1, 100, 15))
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
#np.argwhere(ser > ser.mean())[1]


ser:  [93, 48, 12, 17, 48, 85, 69, 40, 97, 61, 24, 56, 15, 8, 96] mean:  51


In [50]:
# How to get the last n rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
# print rows sums
rowsums = df.apply(np.sum, axis=1)
#last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2], :]

In [51]:
# How to find and cap outliers from a seris or dataframe columns?
ser = pd.Series(np.logspace(-2, 2, 30))
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)



0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.87667222018393


In [52]:
# How to reshape a dataframe to the largest possible square after removing the negative values?

df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]
# Step 2: find side_lenght of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))
# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[32. 33. 29. 48. 24. 40. 38. 13.]
 [26. 46. 31.  8. 16. 30. 15. 48.]
 [21. 24. 27. 46. 48. 22. 10. 48.]
 [14. 28. 20. 24. 30. 10. 43. 47.]
 [13. 17. 10. 11. 43. 39. 46. 27.]
 [17. 46. 12. 35. 45. 36. 36. 24.]
 [47. 45. 33. 44. 25. 40. 24. 20.]
 [32. 20. 25.  9. 12. 35. 47. 25.]]


In [53]:
# How to swap two rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
def swap_rows(df1, i1, i2):
    a,  b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df
print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [55]:
# How to reverse the rows of dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
# Solution 1
df.iloc[::-1, :]
# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [57]:
# How to create one-hot encodings of a categorical variable(dummy variables)?
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [58]:
# Which columns contains the highest number of row_wise maxiumum values?
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  0


In [61]:
# How to create a new columns that contains the row number of nearest column by euclidean distance?
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
import numpy as np
# init outputs
nearest_rows = []
nearest_distance = []
# iterate rows
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {} # init dict to store euclidean dists for current row.
    # irerate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
print(df)

    p   q   r   s nearest_row  dist
a  37  84  21  59           e    97
b  59  53  52  85           g    93
c  77  27  53  64           j    84
d  17  37  15  85           g   109
e  74  36  96  64           d   101
f  48  50  43  90           g    98
g  88  44  21   3           j   115
h  69  26  22  54           j    89
i  65  20   4  28           j   109
j  20  87  59  76           g   115
